In [1]:
## Importar librerias necesarias
import pandas as pd
import sqlalchemy as sqlal

In [2]:
## Conexion con la base de datos mariaDB
## modificar usuario, contraseña, host, puerto y el nombre de la base de datos
engine = sqlal.create_engine("mariadb+pymysql://root:admin@127.0.0.1:3307/db_programa_educativo?charset=utf8mb4")
conn = engine.connect()

In [3]:
## Obtener el historial de activos por programa de la BD
query = "SELECT p.nombre AS programa, h.id_estatus_act AS historial_act FROM programas AS p LEFT JOIN inscripciones AS i ON p.id_programa = i.id_programa LEFT JOIN historial_estatus AS h ON i.id_inscripcion = h.id_inscripcion AND h.id_estatus_act IN (1,6)"
prog_activos_hist = pd.read_sql(query, conn)
prog_activos_hist.head()

                 programa  historial_act
0  Bachillerato Ejecutivo            NaN
1    Bachillerato General            NaN
2     Lic. Administración            1.0
3         Lic. Contaduría            1.0
4         Lic. Contaduría            1.0

In [4]:
## Generar la tabla pivot con el total historico de los programas
pivot_programa_hist = (
    prog_activos_hist.groupby(["programa"])['historial_act']
    .count()
    .reset_index()
)
print(pivot_programa_hist)

                 programa  historial_act
0  Bachillerato Ejecutivo              0
1    Bachillerato General              0
2     Lic. Administración              1
3         Lic. Contaduría              2
4          Lic. Logística             13
5      Lic. Mercadotecnia              0
6           Lic. Negocios              7
7   Maestría en Dirección              1
8   Maestría en Educación              2
9      Secundaria Abierta              2

In [5]:
## Obtener los inscritos que estan activos por programa de la BD
query = "SELECT p.nombre AS programa, i.id_estatus AS tot_activos, h.id_estatus_act FROM programas AS p LEFT JOIN inscripciones AS i ON p.id_programa = i.id_programa AND i.id_estatus IN (1,6) LEFT JOIN historial_estatus AS h ON i.id_inscripcion = h.id_inscripcion AND h.id_estatus_act IN (1,6)"
prog_activos = pd.read_sql(query, conn)
prog_activos.head()

                 programa  tot_activos  id_estatus_act
0  Bachillerato Ejecutivo          NaN             NaN
1    Bachillerato General          NaN             NaN
2     Lic. Administración          NaN             NaN
3         Lic. Contaduría          NaN             NaN
4          Lic. Logística          6.0             1.0

In [6]:
## Generar la tabla pivot de los programas activos
pivot_programa_act = (
    prog_activos.groupby(["programa"])['tot_activos']
    .count()
    .reset_index()
)
print(pivot_programa_act)

                 programa  tot_activos
0  Bachillerato Ejecutivo            0
1    Bachillerato General            0
2     Lic. Administración            0
3         Lic. Contaduría            0
4          Lic. Logística            2
5      Lic. Mercadotecnia            0
6           Lic. Negocios            3
7   Maestría en Dirección            0
8   Maestría en Educación            2
9      Secundaria Abierta            2

In [7]:
## Unir las tablas pivot (pivot_programa_hist y pivot_programa_act)
pivot_programas = pd.merge(pivot_programa_hist, pivot_programa_act, on='programa')

## Calcular la tasa de los alumnos activos
pivot_programas['tasa_activos'] = (pivot_programas['tot_activos'] / pivot_programas['historial_act'] * 100).round(2)

## Convertir los NaN en 0 en la columna tasa_activos
pivot_programas['tasa_activos'] =  pivot_programas['tasa_activos'].fillna(0)
print(pivot_programas)

                 programa  historial_act  tot_activos  tasa_activos
0  Bachillerato Ejecutivo              0            0          0.00
1    Bachillerato General              0            0          0.00
2     Lic. Administración              1            0          0.00
3         Lic. Contaduría              2            0          0.00
4          Lic. Logística             13            2         15.38
5      Lic. Mercadotecnia              0            0          0.00
6           Lic. Negocios              7            3         42.86
7   Maestría en Dirección              1            0          0.00
8   Maestría en Educación              2            2        100.00
9      Secundaria Abierta              2            2        100.00